version: '3.5'

services:
  laravel-api:
    image: franksipoli/apilaravel
    container_name: laravel-api
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend-network:
                aliases:
                  - api
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bl4bl4@l3mbr4
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend-network:
                aliases:
                  - mysql-db

networks:
  backend-network:
    external: true